name: CI_Playwright
on: 
  push
  jobs:
  run_tests:
    name: Run my Playwright tests
    runs-on: ubuntu-latest

    steps:
    name: Get the code
  uses: actions/checkout@v3

  name: Install Node.js
  uses: actions/setup-node@v3
  with:
    node-version: '18'
    name: Install dependencies
  run: cd client && npm ci && cd ../server && npm ci && cd ..

  name: Install browsers
  run: cd client && npx playwright install --with-deps && cd ..

  name: Run Playwright
  run: cd client && npx playwright test example